### ISSUE TITLE
10m-pass.sh line 35: instagram-py: command not found

### ISSUE THREAD

**Issue by Jayaprakash1214** [krishealty/venom-instagram-bruteforce#2]
Please fix this

![Screenshot_20240615-130947_Termux.jpg](https://github.com/krishealty/venom-instagram-bruteforce/assets/157594637/b9652f75-31d3-40c0-a4d4-fb38dc2019f8)

**Comment by krishealty** [comment]
Please ensure that you have the latest version of python3 installed on your machine, if problem persists, please open a new issue and I'll look out at the script for the necessary changes, thanks for using.
