### ISSUE TITLE
This Tool Not Support For My Device Plzzz Help!

### ISSUE THREAD

**Issue by Jayaprakash1214** [krishealty/venom-instagram-bruteforce#3]
Bro I need this Insta id:@ _vip._.edits_ pass details please help me!

That tool not support my device 
I many time try but not working on my device. please use your device and find the pass details please help me bro i trust you bro! Plzzz!

Reason:that id scam my money but i can't revenge i am kid i need your help please bro!

Contact me: my telegram id: @mejp1214 

Wait your reply please response!![Screenshot_20240615-144410_Termux.jpg](https://github.com/krishealty/venom-instagram-bruteforce/assets/157594637/f82c3fdc-1dd3-4715-a793-3b76445d7099)

![Screenshot_20240615-143503_Termux.jpg](https://github.com/krishealty/venom-instagram-bruteforce/assets/157594637/b960b375-50e1-4558-a891-eb3f5e756c5f)

**Comment by krishealty** [comment]
updated it.
